### ISSUE TITLE
Vulnerabilities found on dependencies

### ISSUE THREAD

**Issue by webocs** [IngSisFAI/volunt-app#1]
Dos dependencias estan outdated y tienen vulnerabilidades

![image](https://user-images.githubusercontent.com/2563911/37415160-80c6ed8a-2789-11e8-94ef-1b639187724f.png)

**Comment by morexlt** [comment]
Sisi a mi también me llegan, por ahora no es prioritario por estar en desarrollo

**Comment by JuampiOrlando** [comment]
Resuelto en https://github.com/IngSisFAI/volunt-app/pull/2 !
